### ISSUE TITLE
A game with no button "Claimed" and not linked to the Steam store

### ISSUE THREAD

**Issue by woctezuma** [petetnt/neogaf-monkeybot#14]
In the following giveaway, the game "Joana's Life" is neither showing a button "Claimed" nor linked to the Steam store: http://www.neogaf.com/forum/showpost.php?p=231329302&postcount=616

Screenshot as follows:
![ksgflbh 1](https://cloud.githubusercontent.com/assets/570669/23513862/d6fc0070-ff65-11e6-9fea-c9fcbb6d6f7d.png)

**Comment by woctezuma** [comment]
The problem has to be with escaping the quote.

**Comment by petetnt** [comment]
Yep, I think so too.

**Comment by nikop** [comment]
It's caused by:

escapeHtml, it escapes ' while it's not escaped by NeoGAF code. I guess easy solution is to remove this character from escaped list.

Also noticed that code allows XSS code injection. (#15)

**Comment by woctezuma** [comment]
You are right.

**Comment by petetnt** [comment]
Fix in #16 right?

**Comment by woctezuma** [comment]
Yes.
